name: aws

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "18.221.17.99"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/LEMMA"

      - name: Install dependencies and restart app with PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 18.221.17.99
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/LEMMA
            npm install pm2
            npm install
            cp ../.env .
            npm run build
            pm2 restart lemma || pm2 start --no-autorestart "PORT=3000 node -r dotenv/config build" --name lemma
            pm2 save
